# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - 'CODE_OF_CONDUCT.md'
      - 'CONTRIBUTING.md'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'

#permissions:
#  contents: write

jobs:
  build:

    runs-on: macos-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Gradle
      id: cache-gradle
      uses: actions/cache@v2
      with:
        path: |
         ~/.gradle/caches
         ~/.gradle/wrapper
         /Users/runner/.konan
        key: "gradle-cache"

#    - name: Bump version and push tag
#        id: create_tag
#        uses: hennejg/github-tag-action@v4.1.jh1
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          release_branches: "main"
##          dry_run: true


    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        dry_run: "${{ github.ref != 'refs/heads/main' || startsWith(github.event.head_commit.message, '[DOCS]') || startsWith(github.event.head_commit.message, '[docs]') }}"

    - name: Set flavored version
      run: |
        echo "BUILD_NUMBER=-alpha.${{ github.run_number }}" >> $GITHUB_ENV
      if: startsWith(github.event.pull_request.title, '[DOCS]') != true && github.ref != 'refs/heads/main'

    - name: Build Artifacts
      run: |
        echo ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }} | base64 -d > secret_key 
        bash scripts/publish.sh ${{ steps.tag_version.outputs.new_version }}${{env.BUILD_NUMBER}} '--sonatype'
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
        SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        SIGNING_SECRET_KEY_RING_FILE: "/Users/runner/work/kmp-annotations/kmp-annotations/secret_key"
        SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

#    - name: Create a GitHub release
#      if: ${{ github.ref == 'refs/heads/main' }}
#      uses: ncipollo/release-action@v1
#      with:
#        tag: ${{ steps.tag_version.outputs.new_tag }}
#        name: ${{ steps.tag_version.outputs.new_tag }}
#        body: ${{ steps.tag_version.outputs.changelog }}


    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: build/.m2/
        retention-days: 2
    # The USERNAME and TOKEN need to correspond to the credentials environment variables used in
    # the publishing section of your build.gradle
#     - name: Publish to GitHub Packages
#       uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
#       with:
#         arguments: publish
#       env:
#         USERNAME: ${{ github.actor }}
#         TOKEN: ${{ secrets.GITHUB_TOKEN }}
